---
title: "Aula 12 - Modelos de médias móveis, Modelos auto-regressivos e de médias móveis e modelos ARIMA"
subtitle: "Material fortemente baseado no livro de Morettin e Toloi (2004)"
author: "Renato Rodrigues Silva"
institute: "Universidade Federal de Goiás."
date: "(updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

    
---
class: middle
##Modelos de médias móveis

- Um modelo de médias móveis de ordem $q$, é definido por meio de:

\begin{align}
Z_t  =& \mu + a_t -\theta_1 a_{t-1} - \ldots  -\theta_q a_{t-q} \\
 =& (1 - \theta_1 B - \ldots - \theta_q B^q) a_t \\
 =& \theta(B) a_t 
\end{align}
em que $\theta(B) = (1 - \theta_1 B - \ldots - \theta_q B^q).$ 




---
class: middle
###Condições de Estacionariedade - MA(q)

- Dado que $\psi(B) = 1 - \theta_1 B - \ldots -\theta_q B^q,$ não há restrições sobre os parâmetros $\theta_j$ para que o processo seja estacionário.

###Condições de Invertibilidade - MA(q)

- Usando um argumento completamente similar ao que foi feito aos modelos
auto-regressivos, no caso de estacionariedade.

- Pode-se verificar que a condição de invertibilidade para um modelo de médias móveis de ordem $q$ é que as raízes da equação característica $\theta(B) = 0$ esteja fora do círculo unitário.

- Nestas condições, um modelo $MA(q)$ é equivalente a um modelo AR de ordem infinita.


---
class: middle
###Variância

Temos que a função de autocovariância é dada por:

\begin{align}
\gamma_j =& E[\tilde{Z}_t, \tilde{Z}_{t-j}] \\
=& E\left[\left( a_t - \sum_{k=1}^q \theta_k a_{t-k}  \right)\left(  a_{t-j} - \sum_{l=1}^q \theta_l a_{t-j-l}  \right)\right] \\
=& E[a_t a_{t-j}] - \sum_{k=1}^q \theta_k E[a_{t-j}a_{t-k}] - \sum_{l=1}^q \theta_l E[a_t a_{t-j-l}] + \sum_{k=1}^q\sum_{l=1}^q \theta_k \theta_l E[a_{t-k}a_{t-j-l}]
\end{align}


Lembrando que 

\begin{align}
E[a_t a_{t-j}] = \left\{\begin{array}{cc} 
\sigma^2_a,   & j = 0 \\
0, & j \neq 0.   
\end{array}\right.
\end{align}

---
class: middle
###Variância

Logo, a variância do modelo é dada por

$$\gamma_0 =  \sigma^2_a +  \sum_{l=1}^q \theta_l^2 \sigma_a^2 = (1 + \theta_1^2 + \ldots + \theta^2_q) \sigma_a^2.$$
- Pois, para $j=0$, tem-se $E[a_t a_{t-j}] = E[a_t a_{t}]$. Para $j=0$ e $k=l$ tem-se  $\theta_k \theta_l E[a_{t-k}a_{t-j-l}] = \theta_l^2\sigma_a^2$, cujo o número de ocorrência é igual a $q$,


---
class: middle
###Função de autocorrelação

\begin{align}
\gamma_j = E[a_t a_{t-j}] - \sum_{k=1}^q\theta_k E[a_{t-j}a_{t-k}] - \sum_{l=1}^q \theta_l E[a_t a_{t-j-l}] + \sum_{k=1}^q\sum_{l=1}^q \theta_k \theta_l E[a_{t-k}a_{t-j-l}]
\end{align}

vemos que podemos reescrever $\gamma_j$ da seguinte forma

\begin{align}
\gamma_j = \left\{\begin{array}{cc} 
\left( -\theta_j + \sum_{l=1}^{q-j} \theta_j \theta_{j+l}\right) \sigma^2_a   & j = 1, \ldots,q, \\
0, & j > q.   
\end{array}\right.
\end{align}


- Pois para $j = 1, \ldots, q$, temos $E[a_t a_{t-j}] = 0$, para $k=j$  temos $\sum_{k=1}^q \theta_k E[a_{t-j}a_{t-k}] = -\theta_j,$ com ocorrência igual a 1 e para $k = j + l$ temos $\sum_{k=1}^q\sum_{l=1}^q \theta_k \theta_l E[a_{t-k}a_{t-j-l}] =  \theta_j \theta_{j+l}\sigma_a^2$
com ocorrência igual a $q-j.$


---
class: middle
###Função de autocorrelação


- Logo a função de autocorrelação de um modelo de médias móveis é dado por:

\begin{align}
\rho_j = \left\{\begin{array}{cc} 
\frac{-\theta_j + \theta_1 \theta_{j+1} + \theta_2 \theta_{j+2} + \ldots + \theta_{q-j} \theta_q }{1 + \theta_1^2 + \ldots + \theta_q^2}   & j = 1, \ldots,q, \\
0, & j > q.   
\end{array}\right.
\end{align}

- A fac de um processo $MA(q)$ é igual a zero para "lags" maiores do que $q$, ao contrário do que acontece com um processo AR.

---
class: middle
##Exemplo 1 - Modelo MA(1) (Morettin e Toloi, 2004) 

- Considere o seguinte modelo:

$$\tilde{Z}_t = a_t - \theta a_{t-1}$$
ou 

$$\tilde{Z}_t = (1 - \theta B) a_{t},$$
de modo que $\theta(B) = 1 - \theta B.$ Como $\psi(B) = 1 - \theta B$ é finito, o processo é sempre estacionário, de acordo com a Proposição da aula 10.

- Como $a_t = [\theta(B)]^{-1}\tilde{Z}_t = \frac{1}{1-\theta B} \tilde{Z}_t,$

obtemos a forma invertível

$$\tilde{Z}_t = -\theta \tilde{Z}_{t-1} -\theta^2 \tilde{Z}_{t-2} - \ldots + a_t$$

se $|\theta| < 1$, ou seja, a série $\pi(B) = \theta^{-1}(B)$ acima converge para $|B| \leq 1.$

- Isto é equivalente a dizer que as raízes da equação $\theta(B) = 1 - \theta B = 0$ estão fora do círculo unitário.


---
class: middle
##Exemplo 2 - Modelo MA(2) (Morettin e Toloi, 2004) 

- Para um processo $MA(1),$ a condição de invertibilidade é $-1 < \theta < 1.$

- A variância é dada por: $\sigma_Z^2 = (1 + \theta^2)\sigma_a^2$

e a fac se obtém de

\begin{align}
\rho_j = \left\{\begin{array}{cc} 
\frac{-\theta}{1 + \theta^2}   & j = 1, \\
0, & j \geq 2.   
\end{array}\right.
\end{align}

---
class: middle
##Exemplo 2 - Modelo MA(2) (Morettin e Toloi, 2004) 

- Considere 

$$\tilde{Z}_t = a_t -\theta_1 a_{t-1} - \theta_2 a_{t-2},$$

- O processo resultante será estacionário para quaisquer valores de $\theta_1$ e $\theta_2$, mas invertível somente se as raízes características de $\theta(B) = 1 - \theta_1 B - \theta_2 B^2 = 0$
estiverem fora do círculo unitário.

A região de invertibilidade  é dada por:

\begin{align}
\rho_j = \left\{\begin{array}{c} 
\theta_2 + \theta_1 < 1,   \\
\theta_2 - \theta_1 < 1, \\
-1 < \theta_2 < 1.
\end{array}\right.
\end{align}
equivalente a região de estacionariedade encontrada para $AR(2).$

---
class: middle
##Exemplo 2 - Modelo MA(2) (Morettin e Toloi, 2004) 

A variância e função de autocorrelação são dadas por:

\begin{align}
\gamma_0 =& (1 + \theta_1^2 + \theta_2^2) \sigma^2_a \\
\rho_1 =& \frac{-\theta_1(1 - \theta_2)}{1 + \theta_1^2 + \theta_2^2} \\
\rho_2 =& \frac{-\theta_2}{1 + \theta_1^2 + \theta_2^2} \\
\rho_j =& 0, \phantom{111} j = 3,4,5 \ldots
\end{align}

---
class: inverse, middle, center
##Modelos autoregressivos e de médias móveis


---
class: middle
##Modelos autoregressivos e de médias móveis

- Os modelos $ARMA(p,q)$ da forma:

\begin{align}
\tilde{Z}_t =& \phi_1 \tilde{Z}_{t-1} + \ldots + \phi_p \tilde{Z}_{t-p}+ a_t - \theta_1 a_{t-1} - \ldots - \theta_q a_{t-q}. \\
\phi(B) \tilde{Z}_t =& \theta(B) a_t.
\end{align}

###Estacionariedade e Invertibilidade (Modelo ARMA)

- A importância do processo ser invertível pode vista [aqui](https://stats.stackexchange.com/questions/50682/what-is-the-intuition-of-invertible-process-in-time-series) 

- O processo é estacionário se as raízes de $\phi(B) = 0$ caírem todas as fora do círculo unitário e o processo é invertível se todas as raízes de $\theta(B) = 0$ caírem fora do círculo unitário.

---
class: middle
##Função de Autocorrelação - Modelos ARMA

A função de autocorrelação é dada por:

\begin{align}
\gamma_j =& E[\tilde{Z}_t \tilde{Z}_{t-j}] \\
=& \phi_1 E[\tilde{Z}_{t-1} \tilde{Z}_{t-j}] + \ldots + \phi_p E[\tilde{Z}_{t-p} \tilde{Z}_{t-j}] \\
&- E[a_t \tilde{Z}_{t-j}] -
\theta_1 E[a_{t-1} \tilde{Z}_{t-j}] - \ldots -\theta_q E[a_{t-q} \tilde{Z}_{t-j}] 
\end{align}

- Agora note que $Z_{t-j}$ só depende dos choques ocorridos até o instante $t-j$, pois

\begin{align}
\tilde{Z}_{t-j} =& \phi_1 \tilde{Z}_{t-j-1} + \ldots + \phi_p \tilde{Z}_{t-j-p}+ a_{t-j} - \theta_1 a_{t-j-1} - \ldots - \theta_q a_{t-j-q}.
\end{align}
Logo,

\begin{align}
\gamma_{za}(j) = E[a_t \tilde{Z}_{t-j}] = \left\{\begin{array}{cc} 
=0  & j > 0  \\
\neq 0 & j \leq 0.
\end{array}\right.
\end{align}

---
class: middle
##Função de Autocorrelação - Modelos ARMA

Assim, temos que a função de autocovariância é dada por:

\begin{align}
\gamma_j = \phi_1 \gamma_{j-1} + \phi_2 \gamma_{j-2} + \ldots + \phi_p \gamma_{j-p}, \phantom{111} j > q.
\end{align}

A função de autocorrelação é obtida de 

\begin{align}
\rho_j = \phi_1 \rho_{j-1} + \phi_2 \rho_{j-2} + \ldots + \phi_p \rho_{j-p}, \phantom{111} j > q.
\end{align}

- Do que se deduz que as autocorrelações de "lags" $1,2, \ldots, q$ serão afetadas diretamente pelos parâmetros de médias móveis, mas para $j > q$ as mesmas comportam-se como nos modelos autoregressivos.

- Pode-se verificar que se $q < p$ a fac consiste numa mistura de exponenciais e/ou senoides amortecidas, entretanto $q \geq p$, os primeiros $q-p-1$ valores $\rho_0, \rho_1, \ldots, \rho_{q-p}$ não seguirão esse padrão.


---
class: middle
##Exemplo 3 - Modelo ARMA(1,1) (Morettin e Toloi, 2004) 

- O modelo $ARMA(1,1)$ é dado por:

$$\tilde{Z}_t = \phi \tilde{Z}_{t-1} + a_t - \theta a_{t-1},$$

####Condições de estacionariedade e invertibilidade

- Segue-se que a condição de estacionariedade para um processo $ARMA(1,1)$ é a mesma que para um processo $AR(1)$ e a condição de invertibilidade é a mesma que para um processo $MA(1)$.

---
class: middle
##Exemplo 3 - Modelo ARMA(1,1) (Morettin e Toloi, 2004) 

####Função de autocorrelação

- Para calcularmos a função de autocorrelação do processo ARMA(1,1) é mais fácli escrevê-lo como um processo linear geral

\begin{align}
\tilde{Z}_t =& \phi_1 \tilde{Z}_{t-1} + a_t - \theta_1 a_{t-1} \\
(1- \phi_1 B)\tilde{Z}_{t} &= (1- \theta_1 B) a_t \\
\tilde{Z}_{t} =& \frac{1}{(1- \phi_1 B)} (1- \theta_1 B) a_t \\
\tilde{Z}_{t} =& (1 + \phi_1 B + \phi_1^2 B^2 + \ldots)(1 - \theta_1 B) a_t \\
\tilde{Z}_{t} =& \left[1 + \phi_1 B + \phi_1^2 B^2 + \ldots - \theta_1 B - \theta_1 \phi_1 B^2 - \theta_1 \phi_1^2 B^3 \ldots \right] a_t \\
\tilde{Z}_{t} =& \left[ 1 + (\phi_1 - \theta_1) B + (\phi_1^2 - \phi_1\theta_1)B^2 + \ldots \right] a_t \\
\tilde{Z}_{t} =& \left[ 1 + (\phi_1 - \theta_1) B + (\phi_1 - \theta_1) \phi_1 B^2 + (\phi_1 - \theta_1)\phi_1^2 B^3 \right] a_t \\
\tilde{Z}_{t} =& a_t + (\phi_1 - \theta_1) \sum_{j=1}^{\infty} \phi^{j-1} a_t.
\end{align}



---
class: middle
##Exemplo 3 - Modelo ARMA(1,1) (Morettin e Toloi, 2004) 

- Considerando que o processo linear geral é dado por $\tilde{Z}_t = \sum_{j=0}^{\infty}\psi_j a_{t-j}$ com facv $\gamma_j = \sigma_a^2 \sum_{j=0}^{\infty}\psi_j^2.$ 

- O modelo $ARMA(1,1)$ pode ser considerado um processo linear geral com 
$\psi_0 = 1$ e $\psi_j = (\phi_1 - \theta_1)\phi_1^{j-1}.$ Logo,

\begin{align}
\gamma_0 =& \sigma_a^2\sum_{j=0}^{\infty} \psi_j^2 \\
=& \sigma_a^2 \left[ 1^2 + (\phi_1 - \theta_1)^2 \sum_{j=1}^{\infty } \phi^{2 (j-1)} \right] \\
=& \sigma_a^2 \left[ 1^2 + \frac{(\phi_1 - \theta_1)^2}{1-\phi_1^2} \right] = \sigma_a^2 \left[  \frac{(1-\phi_1^2)}{(1-\phi_1^2)} + \frac{(\phi_1 - \theta_1)^2}{(1-\phi_1^2)} \right] \\
&= \sigma_a^2 \frac{1+\theta_1^2-2\phi_1\theta_1}{(1-\phi_1^2)}.
\end{align}

---
class: middle
##Exemplo 3 - Modelo ARMA(1,1) (Morettin e Toloi, 2004) 


\begin{align}
\gamma_1 =& \sigma_a^2\sum_{i=0}^{\infty} \psi_i \psi_{i+j} \\
=& \sigma_a^2 \left[1(\phi_1 - \theta_1) + (\phi_1 - \theta_1)(\phi_1 - \theta_1)\phi_1 + (\phi_1 - \theta_1)(\phi_1 - \theta_1)\phi_1^2 + \ldots \right] \\
=& \sigma_a^2 \left[ (\phi_1 - \theta_1) + (\phi_1 - \theta_1)^2\phi_1\sum_{j=0}^{\infty} \phi_1^{2j} \right] \\
=& \sigma_a^2 \left[ (\phi_1 - \theta_1) + \phi_1 \frac{(\phi_1 - \theta_1)^2}{(1 - \phi_1^2)} \right] \\
=& \sigma_a^2 \left[ \frac{(\phi_1 - \theta_1)(1 - \phi_1^2)}{(1 - \phi_1^2)} + \phi_1 \frac{(\phi_1 - \theta_1)^2}{(1 - \phi_1^2)} \right] \\
=& \sigma_a^2 \left[ \frac{(\phi_1 - \theta_1)(1 - \phi_1^2 + \phi_1^2 - \phi_1\theta_1)}{(1 - \phi_1^2)}  \right] =  \sigma_a^2 \left[ \frac{(\phi_1 - \theta_1)(1 - \phi_1\theta_1)}{(1 - \phi_1^2)}  \right]\\
\end{align}

---
class: middle
##Exemplo 3 - Modelo ARMA(1,1) (Morettin e Toloi, 2004) 

- Para $j > 1$, temos

$$\rho_j = \phi_1 \rho_{j-1}$$

- A presença de um termo de médias móveis entra somente na determinação de $\rho_1$. 

- As demais autocorrelações são afetadas somente pela parte auto-regressiva do modelo.

---
class: inverse, middle, center
##Modelos auto-regressivos integrados e de médias móveis

---
class: middle
##Modelos auto-regressivos integrados e de médias móveis

###Modelos não-estacionários

- Os modelos AR, MA e ARMA são apropriados para descrever séries estacionárias. 

- No entanto, na prática muitas séries não são estacionárias.

- Os modelos auto-regressivos integrados e de médias móveis (ARIMA) são apropriados para representar séries cujo comportamento seja não explosivo.


---
class: middle
##Modelos auto-regressivos integrados e de médias móveis

- Uma forma matemática de representar um modelo ARIMA de ordem $(p,q,d)$ é dada por:

\begin{align}
\varphi(B)Z_t =& \theta(B)a_t \\
\phi(B)(1 - B)^d Z_t =& \theta(B)a_t \\
\phi(B)\Delta^dZ_t =& \theta(B)a_t \\ 
\end{align}
em que $d$ é o número de diferenças.

- Portanto, o modelo supõe que a d-ésima diferença da série $Z_t$ pode ser representada por um modelo ARMA, estacionário e invertível.

- Na maioria dos casos usuais, $d = 1$ ou $d = 2,$ que correspondem a dois casos interessantes e comuns de não-estacionariedade homogênea:

a. séries não estacionárias quanto ao nível: normalmente uma diferença basta

b.  séries não estacionárias quanto à inclinação: necessário tomar a segunda diferença.



